name: my workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run containers with docker-compose
        run: make up

      - name: Shut down containers
        if: always()
        run: make down-v
