name: my workflow

on:
    workflow_dispatch:
        inputs:
            run-job-3:
                description: Run job 3
                type: boolean
                required: true

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "Hello World"

  job-2:
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
      - name: say-welcome
        run: echo "Welcome to Github Actions"

  job-3:
    runs-on: ubuntu-latest
    needs: [job-2]
    if: github.event.inputs.run-job-3 == 'true'
    steps:
      - name: echo-context
        env:
            CONTEXT: ${{toJson(github)}}
        run: echo $CONTEXT

  job-4:
    runs-on: ubuntu-latest
    needs: [job-2, job-3]
    steps:
      - name: say-bye
        run: echo "Bye World"
name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run containers with docker-compose
        run: make up

      - name: Shut down containers
        if: always()
        run: make down-v
