name: my workflow

on:
    workflow_dispatch:
        inputs:
            run-job-3:
                type: boolean
                required: true
               

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "Hello World"

  job-2:
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
      - name: say-welcome
        run: echo "Welcome to Github Actions"
    
  job-3:
    runs-on: ubuntu-latest
    needs: [job-2]
    if: ${{ github.event.inputs.run-job-3 }}
    steps:
      - name: say-goodbye
        run: echo "Goodbye World"
